export const CLASS_SET = 'CLASS_SET';
export const CLASSES_SET = 'CLASSES_SET';
export const CLASS_DELETE = 'CLASS_DELETE';
export const CLASS_STATE_CLEAR = "CLASS_STATE_CLEAR";

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';