export const CLASS_SET = 'CLASS_SET';
export const CLASSES_SET = 'CLASSES_SET';
export const CLASS_DELETE = 'CLASS_DELETE';
export const CLASS_STATE_CLEAR = "CLASS_STATE_CLEAR";

export const SUBJECT_SET = 'SUBJECT_SET';
export const SUBJECTS_SET = 'SUBJECTS_SET';
export const SUBJECT_DELETE = 'SUBJECT_DELETE';
export const SUBJECT_STATE_CLEAR = "SUBJECT_STATE_CLEAR";

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';