export const CLASS_SET = 'CLASS_SET';
export const CLASSES_SET = 'CLASSES_SET';
export const CLASS_DELETE = 'CLASS_DELETE';
export const CLASS_STATE_CLEAR = "CLASS_STATE_CLEAR";

export const SUBJECT_SET = 'SUBJECT_SET';
export const SUBJECTS_SET = 'SUBJECTS_SET';
export const SUBJECT_DELETE = 'SUBJECT_DELETE';
export const SUBJECT_STATE_CLEAR = "SUBJECT_STATE_CLEAR";

export const LESSON_SET = 'LESSON_SET';
export const LESSONS_SET = 'LESSONS_SET';
export const LESSON_APPEND = 'LESSON_APPEND';
export const LESSON_DELETE = 'LESSON_DELETE';
export const LESSON_UPDATE = 'LESSON_UPDATE';
export const LESSON_STATE_CLEAR = "LESSON_STATE_CLEAR";

export const ACCOUNT_SET = 'ACCOUNT_SET';
export const ACCOUNTS_SET = 'ACCOUNTS_SET';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const EXERCISE_SET = 'EXERCISE_SET';
export const EXERCISES_SET = 'EXERCISES_SET';
export const EXERCISE_DELETE = 'EXERCISE_DELETE';
export const EXERCISE_STATE_CLEAR = "EXERCISE_STATE_CLEAR";

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';